import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menu from "./menu/layout";
import Home from "./page";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
         <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        data-smart-converter-loaded="true"
      >
        
          <Menu/>

         
            {children}  
          
        
      </body>
    </html>
  );
}
